project:
  type: website
  output-dir: docs

website:
  title: "MGV"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - open_source.qmd
      - tutorials.qmd
      - publications.qmd
      - CV.qmd
        
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true